#!/bin/bash

mkdir -p orig

VER=1.19.0-x86_64-unknown-linux-gnu
[ -e orig/rustc-$VER.tar.gz ] || (cd orig && wget https://static.rust-lang.org/dist/rustc-$VER.tar.gz)

(cd orig && tar xzf rustc-$VER.tar.gz)

diffoscope --markdown report.md rust/build/x86_64-unknown-linux-gnu/stage2/bin/rustc orig/rustc-$VER/rustc/bin/rustc
